export enum DisplayOptions {
  NAME = "name",
  MAIN_LINE = "mainLine",
  BADGES = "badges",
  DESCRIPTION = "description",
  ADMONITIONS = "admonitions",
  ADMONITIONS_BY_TYPE = "admonitionsByType",
  IMPORT = "import",
  EXAMPLE = "example",
  PREVIEW = "preview",
  PARAMETERS = "parameters",
  PARAMETER = "parameter",
  METHODS = "methods",
  METHOD = "method",
  RETURNS = "returns",
  TYPE_REFERENCES = "typeReferences",
  ADDITIONAL_LINKS = "additionalLinks",
}
