import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { apiOverviewSection } from "./src/apis";
import { sections } from "./src/sections";
import { guides } from "./src/guides";

const sidebars: SidebarsConfig = {
  // Docs
  ...sections.reduce<SidebarsConfig>((acc, section) => {
    acc[section.dir] = [{ type: "autogenerated", dirName: section.dir }];
    return acc;
  }, {}),
  // Guides
  ...guides.reduce<SidebarsConfig>((acc, section) => {
    acc[`guides/${section.dir}`] = [{ type: "autogenerated", dirName: `guides/${section.dir}` }];
    return acc;
  }, {}),
  // API
  ...[
    apiOverviewSection,
    ...sections.filter((section) => section.isPackage),
  ].reduce<SidebarsConfig>((acc, section) => {
    const dir = `api/${section.dir}`;
    acc[dir] = [{ type: "autogenerated", dirName: dir }];
    return acc;
  }, {}),
  // Showcase
  showcase: [{ type: "autogenerated", dirName: "showcase" }],
};

// eslint-disable-next-line import/no-default-export
export default sidebars;
